theme: jekyll-theme-midnight
title: cipherutils
description: solve trivial ciphers in the blink of an eye
show_downloads: true
github:
  owner_url: https://github.com/tubbo/cipherutils
  owner_name: tubbo
  zip_url: https://github.com/tubbo/cipherutils/archive/master.zip
  tar_url: https://github.com/tubbo/cipherutils/archive/master.tar.gz
