name: Build
on: [push]
env:
  GO11MODULES: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - 386
        os:
          - darwin
          - linux
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - run: gem install ronn
      - run: make
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: make dist
        env:
          VERSION: ${{ github.sha }}
      - uses: actions/upload-artifact@v2
        with:
          name: cipherutils-${{ matrix.os }}-${{ matrix.arch }}-${{ github.sha }}
          path: dist/cipherutils-${{ github.sha }}
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-ruby@v1
  #     - uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.13.x
  #     - run: gem install ronn
  #     - run: make
  #     - run: make check
