name: Publish
on:
  push:
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - 386
        os:
          - darwin
          - linux
    steps:
      - uses: actions/checkout@v1
      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/setup-ruby@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - run: gem install ronn
      - run: make
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: make dist
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: dist/cipherutils-${{ steps.get_version.outputs.version }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          path: dist
      - name: Create Release
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
